policies:
  # The following policies are designed to work from GitHub action workflows.
  # This means that before running any Updatecli command, we need the two following environment variables set:
  # 
  #   GITHUB_TOKEN: Set to a personal access token
  #   GITHUB_ACTOR: Set to the username associated with the GITHUB_TOKEN
  # 
  # Instruction to retrieve your PAT is documented on https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  - name: Handle docusaurus versioning
    policy: ghcr.io/olblak/rancherlabs-policies/docusaurus/versioning:0.2.0@sha256:47f5704c49384ab6aee972a8097d252f95b22a00eba91123dbc2a184c85fbb5f
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/fleet.yaml
  - name: Handle releasepost
    policy: ghcr.io/olblak/rancherlabs-policies/docusaurus/releasepost:0.5.1@sha256:5190f9af490d5e7f6c16bb50048c43fc8c3c8e144814a5ef684b8b05c2c4b780
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/fleet.yaml
  - name: Handle Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.8.0@sha256:99e9e61b501575c2c176c39f2275998d198b590a3f6b1fe829f7315f8d457e7f
    values:
      - updatecli/values.d/scm-2.yaml
